home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.index, name='home'),
    path('producto/', views.Producto,name='producto'),
]

petshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('carrito/',include('ordenes.urls')),
    path('producto/',include('productos.urls')),
    path('contacto/',include('contacto.urls')),
    path('captcha/',include('captcha.urls')),
    path('tienda/',include('tienda.urls')),
    path('accounts/', include('registration.backends.default.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from tienda import views
from tienda.views import VerImagenes
urlpatterns = [
    path('cargar/',views.cargar_imagen, name="cargar"),
    path('<int:producto_id>/ver/',views.ver_imagen, name="ver"),
    path('verproductos/',VerImagenes.as_view(), name="verproductos"),
]

ordenes/models.py
from django.db import models

# Create your models here.
from productos.models import Producto
from home.models import Cliente

class Orden(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, blank=True, null=True)
    fecha_de_creacion = models.DateTimeField('Fecha de orden')
    completada = models.BooleanField(default=False, null=True, blank=False)
    id_transaccion = models.CharField(max_length=200, null=True)

    @property
    def precio_total_carrito(self):
        orden_producto = self.orden_producto_set.all()
        total=sum([producto.total() for producto in orden_producto])
        return total
    @property
    def cantidad_total_carrito(self):
        orden_producto = self.orden_producto_set.all()
        total=sum([producto.cantidad for producto in orden_producto])
        return total
    def __str__(self):
        return self.cliente.nombre + ' - ' + self.id_transaccion

class Orden_Producto(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.SET_NULL, blank=True, null=True)
    orden = models.ForeignKey(Orden, on_delete=models.SET_NULL, blank=True, null=True)
    cantidad = models.IntegerField(default=0, null=True)

    def total(self):
        return self.cantidad*self.producto.precio
    def __str__(self):
        return self.orden.id_transaccion + ' - ' + self.producto.producto

productos/models.py
from django.db import models

# Create your models here.
class Marca(models.Model):
    nombre =models.CharField(max_length=100)
    def __str__(self):
        return self.nombre
class Animal(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.nombre
class Producto(models.Model):
    producto = models.CharField(max_length=50)
    precio= models.DecimalField(max_digits=12,decimal_places=2)
    descripcion = models.TextField(max_length=500, default="")
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True)
    animal = models.ForeignKey(Animal, blank=True, null=True, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, blank=True, null=True, on_delete=models.CASCADE)
    def __str__(self,):
        return self.producto + " --- " +str(self.fecha_publicacion)
""" @property
    def url_imagen(self):
        try:
            url = self.imagen.url
        except:
            url = ''
        return url """

tienda/models.py
from django.db import models

# Create your models here.

tienda/forms.py
from django.forms import ModelForm
from productos.models import Producto

class CargarForm(ModelForm):
    class Meta:
        model=Producto
        fields=['producto','precio','descripcion','fecha_publicacion','imagen']
    def __init__(self, *args, **kwargs):
        super(CargarForm, self).__init__( *args, **kwargs)

tienda/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import View
from productos.models import Producto
from tienda.forms import CargarForm
from django.http import Http404
# Create your views here.
def cargar_imagen(request):
    params={}

    if request.method == 'POST':
        form = CargarForm(request.POST, request.FILES)
        params['form']=form 
        if form.is_valid():
            producto = form.cleaned_data['producto']
            precio = form.cleaned_data['precio']
            descripcion = form.cleaned_data['descripcion']
            fecha_publicacion = form.cleaned_data['fecha_publicacion']
            imagen = form.cleaned_data['imagen']
            nuevo_producto = Producto(producto = producto,precio = precio, fecha_publicacion =fecha_publicacion, imagen=imagen)
            nuevo_producto.save()
            return redirect('home')
    else:
        form = CargarForm()
        params['form'] = form
        return render(request, 'tienda/formulario.html', params)
    
class VerImagenes(View):
    template = "tienda/verproductos.html"

    def get(self, request):
        params={}
        try: 
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params["productos"]=productos

        return render(request, self.template,params)

def ver_imagen(request, producto_id):
    params={}
    try: 
        producto = Producto.objects.get(pk=producto_id)
    except Producto.DoesNotExist:
        raise Http404
    params["producto"]=producto
    return render(request, "tienda/verproducto.html",params)

templates/tienda/formulario.html
{% extends "layout.html" %}
{% load static %}

{% block cuerpo_pagina %}

<div class="container">
    <div class="row justify-content-around align-items-center">
        <div class="col-12 col-md-8">
            <form id="formulario-producto" action="/tienda/cargar/" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div>
                    <label for="id_producto">Producto:</label>
                    <input type="text" name="producto" maxlength="200" required="" id="id_producto">
                </div>
                <div>
                    <label for="id_precio">Precio</label>
                    <input type="text" name="precio" maxlength="200" required="" id="id_precio">  
                </div>
                <div>
                    <label for="id_descripcion">Descripcion</label>
                    <textarea name="descripcion"  required id="id_descripcion"></textarea>  
                </div>
                <div>
                    <label for="id_fecha_publicacion">Fecha de publicacion:</label>
                    <input type="date" name="fecha_publicacion" required="" id="id_fecha_publicacion">    
                </div>
                <div>
                    <label for="id_imagen">Imagen:</label>
                    <input type="file" name="imagen" accept="image/*" id="id_imagen">
                </div>
                <div class="row justify-content-between">
                    <div class="col-4" style="padding-right:30px; margin-top: 20px;">
                        <button type="submit" class=" col-12 btn btn-success"> Submit </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock %}

templates/tienda/verimagen.html
{% extends "layout.html" %}
{% load static %}

{% block cuerpo_pagina %}
    <div class="container ver-producto">
        <div class="row">
            <div class="col-12 col-md-6">
                <img src="/media/{{producto.imagen}}" class="mx-auto"/>
            </div>
            <div class="col-12 col-md-6">
                <h1><strong>{{producto.producto}}</strong></h1>
                <p>Precio:</p>
                <p>${{producto.precio}}</p>
                
            </div>
        </div>
        <div class="row">
            <div class="col-12 descripcion-producto">
                <p> Descripcion:</p>
                <p>{{producto.descripcion}}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/tienda/verimagenes.html
{% extends "layout.html" %}
{% load static %}

{% block cuerpo_pagina %}
    <div class="container">
        <div class="row">
            {% for producto in productos %}
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="card mt-5 mb-5">
                        <img src="/media/{{producto.imagen}}" class="mx-auto"/>
                        <div class="card-body">
                            <h5 class="card-title centrado">{{producto.producto}}</h5>
                            <h4 class="centrado">${{producto.precio}}</h4>
                            <br>
                            <section class="d-flex justify-content-around">
                                <a href="{% url 'ver' producto.id%}" class="btn btn-dark">Ver</a>
                                <a href="#" class="btn btn-primary">Añadir al carrito</a>
                            </section>
                        </div>
                    </div>
                </div>


            {% endfor %}    
        </div>
    </div>
{% endblock %}

templates/tienda/verproducto.html
{% extends "layout.html" %}
{% load static %}

{% block cuerpo_pagina %}
    <div class="container ver-producto">
        <div class="row">
            <div class="col-12 col-md-6">
                <img src="/media/{{producto.imagen}}" class="mx-auto"/>
            </div>
            <div class="col-12 col-md-6">
                <h1><strong>{{producto.producto}}</strong></h1>
                <p>Precio:</p>
                <p style="color: #0092ca;">${{producto.precio}}</p>
                
            </div>
        </div>
        <div class="row">
            <div class="col-12 descripcion-producto">
                <p> Descripcion:</p>
                <p>{{producto.descripcion}}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/tienda/verproductos.html
{% extends "layout.html" %}
{% load static %}

{% block cuerpo_pagina %}
    <div class="container">
        <div class="row">
            {% for producto in productos %}
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="card mt-5 mb-5">
                        <img src="/media/{{producto.imagen}}" class="mx-auto"/>
                        <div class="card-body">
                            <h5 class="card-title centrado">{{producto.producto}}</h5>
                            <h4 class="centrado">${{producto.precio}}</h4>
                            <br>
                            <section class="d-flex justify-content-around">
                                <a href="{% url 'ver' producto.id%}" class="btn btn-dark">Ver</a>
                                <a href="#" class="btn btn-primary">Añadir al carrito</a>
                            </section>
                        </div>
                    </div>
                </div>


            {% endfor %}    
        </div>
    </div>
{% endblock %}